# Generated by Django 4.0.5 on 2022-06-24 03:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supers', '0004_alter_super_super_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='super',
            old_name='super_type',
            new_name='type',
        ),
    ]
