# Generated by Django 4.0.5 on 2022-06-24 03:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supers', '0005_rename_super_type_super_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='super',
            old_name='type',
            new_name='super_type',
        ),
    ]
